# These are supported funding model platforms

<<<<<<< HEAD
github: WoozyStudio
discord: Woozy's YT#2656
youtube: @WoozyStudio
=======
github: [WoozyStudio]
>>>>>>> 1b2ba8d6792e3f84fb9a3d122151b7564930f9b5
